apiVersion: v1
kind: Service
metadata:
    name: inferencelb
spec:
    type: LoadBalancer
    selector:
        app: serviceapi
    ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000