apiVersion: batch/v1
kind: Job
metadata:
  name: trainingjob
spec:
  template:
    metadata:
      name: trainingjob
    spec:
      containers:
      - name: train
        image: yp2141/trainjob:1.0
        volumeMounts:
        - name: pvc
          mountPath: /mnt
      restartPolicy: Never
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvc